# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datatug < Formula
  desc "DataTug – Context-aware data viewer & collaborative query manager for effortless exploration of related data — CLI + Web UI"
  homepage "https://github.com/datatug/datatug-cli"
  version "0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datatug/datatug-cli/releases/download/v0.0.14/datatug_0.0.14_darwin_amd64.tar.gz"
      sha256 "295b6460ed627a5bd29ab2881905b6d7a19d8eeeb07ec03f7b0c3a0489e50c47"

      def install
        bin.install "datatug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datatug/datatug-cli/releases/download/v0.0.14/datatug_0.0.14_darwin_arm64.tar.gz"
      sha256 "de9cf5bd69a13c330e0ffdd7474fb2bfefaf22b571f9fb969d8cd155ad693f16"

      def install
        bin.install "datatug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datatug/datatug-cli/releases/download/v0.0.14/datatug_0.0.14_linux_amd64.tar.gz"
      sha256 "0e152696bf90a9fd960b5f8fabd14782d1d8a074ca53a88d8108571aa7797953"
      def install
        bin.install "datatug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datatug/datatug-cli/releases/download/v0.0.14/datatug_0.0.14_linux_arm64.tar.gz"
      sha256 "37ba82874c094a530f78d8580e2bcda82cd0053177a6fe7a653dfafb1bfdb231"
      def install
        bin.install "datatug"
      end
    end
  end

  test do
    system "#{bin}/datatug", "--version"
  end
end
