# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datatug < Formula
  desc "DataTug – Context-aware data viewer & collaborative query manager for effortless exploration of related data — CLI + Web UI"
  homepage "https://github.com/datatug/datatug-cli"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datatug/datatug-cli/releases/download/v0.8.0/datatug_0.8.0_darwin_amd64.tar.gz"
      sha256 "7e14a8f6a2b50fbc7e6947af75fb21c91b253f4f9abccc73eb73744db393a633"

      define_method(:install) do
        bin.install "datatug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datatug/datatug-cli/releases/download/v0.8.0/datatug_0.8.0_darwin_arm64.tar.gz"
      sha256 "003cbea672aa99fdb4308ad1883bcf36bd4ab291c87e58b44bc536a834ae31cd"

      define_method(:install) do
        bin.install "datatug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datatug/datatug-cli/releases/download/v0.8.0/datatug_0.8.0_linux_amd64.tar.gz"
      sha256 "096b599c6d5bda2d1e46ce60848ee5103c0f4d6aa54f7db6807dc7948261d0f8"
      define_method(:install) do
        bin.install "datatug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datatug/datatug-cli/releases/download/v0.8.0/datatug_0.8.0_linux_arm64.tar.gz"
      sha256 "45ff348a354421126e284a06b0e4af1cd3897d9c9730f5ccc3727894700bda3f"
      define_method(:install) do
        bin.install "datatug"
      end
    end
  end

  test do
    system "#{bin}/datatug", "--version"
  end
end
