# This file was generated by GoReleaser. DO NOT EDIT.
cask "datatug" do
  version "0.11.12"

  on_macos do
    on_intel do
      sha256 "3934b6c8db60a8d732ddfda9985bb33c441a2a4a5073200760502825231c9110"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce82e5015b77beeb487416af3061c137122d91013f5dc6a1f19933f71b9f209a"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "22e2fb96b659230b70d1d384199b049693abc81b96bc6ae5ca97bb75f6b55dcd"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9278497a573540620dd8597cc8ebd00ea0cb265d4e89c7af8178df700f073218"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_linux_arm64.tar.gz"
    end
  end

  name "datatug"
  desc "DataTug – Context-aware data viewer & collaborative query manager for effortless exploration of related data — CLI + Web UI"
  homepage "https://github.com/datatug/datatug-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datatug"

  # No zap stanza required

end
