# This file was generated by GoReleaser. DO NOT EDIT.
cask "datatug" do
  version "0.31.0"

  on_macos do
    on_arm do
      sha256 "89f629193eb30ca5805859501d11dc278c09888eab2028ccc4c2f700acd41067"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "976f2a9d4e81cee46785146e0a5a5bee023692d78021ebe4ff96a2a5606a55b5"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "343d54ca16e9a2c69897e312331fbb6bffb686d4837e1d33675c7f728d8ba73f"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd55208a54d76a4022db56c9b95683b40b1e9649f567ebe4664ff8fb821d3457"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_linux_amd64.tar.gz"
    end
  end

  name "datatug"
  desc "DataTug – Context-aware data viewer & collaborative query manager for effortless exploration of related data — CLI + Web UI"
  homepage "https://github.com/datatug/datatug-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datatug"

  # No zap stanza required
end
