# This file was generated by GoReleaser. DO NOT EDIT.
cask "datatug" do
  version "0.17.1"

  on_macos do
    on_arm do
      sha256 "5dd719159fe23dc940b1811f817bd05eeedd43253ea50b82fec9ae3f4670becb"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5362ee9ceeabe226287d18f4fc300b1c429d49888f775a250b9d2d9433cfa91a"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7d6d875763ad50476bcefb1fdcf897792509b2094d5bfbff690be69dcd7ea69f"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a60c4e57c2a0ef8bfd8068061a40668c5bec073b57f08c96114d25845d62251d"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_linux_amd64.tar.gz"
    end
  end

  name "datatug"
  desc "DataTug – Context-aware data viewer & collaborative query manager for effortless exploration of related data — CLI + Web UI"
  homepage "https://github.com/datatug/datatug-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datatug"

  # No zap stanza required
end
